version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    #environment:
     # MONGO_INITDB_ROOT_USERNAME: myusername
     # MONGO_INITDB_ROOT_PASSWORD: mypassword

volumes:
  mongo_data: ~


# mongosh --host <hostname>:<port> --username <username> --password <password>
